name: Executables

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]


jobs:
  build-backend:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: go build -o ./build/ -v ./server

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: web-tail-${{ matrix.os }}
          path: build
          retention-days: 5

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build:js

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: dist
          retention-days: 5
